apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: PA-DEMO-SEGMENT-IPRANGE-START-END
  description: "Demo IP-Bereich Start–Ende – WinRM 5985 auf 10.0.3.10–10.0.3.20."
  owners:
    - platform@contoso.com
  changeReference: DEMO-SEGMENT-IPRANGE-START-END-001
  tags:
    purpose: demo
    segmentType: ipRange
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: CG-EU-CENTRAL-PA-PROD-01
  destinations:
    - host: "10.0.3.10-10.0.3.20"
      type: ipRange
      ports: ["5985"]
      protocol: tcp
  assignments:
    - principalType: Group
      principalName: SEC-GSA-PA-DEMO-USERS
