apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: PA-DEMO-SEGMENT-IPADDRESS
  description: "Demo IP-Adresse – RDP 3389 auf 192.168.10.42."
  owners:
    - platform@contoso.com
  changeReference: DEMO-SEGMENT-IPADDRESS-001
  tags:
    purpose: demo
    segmentType: ipAddress
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: CG-EU-CENTRAL-PA-PROD-01
  destinations:
    - host: "192.168.10.42"
      type: ipAddress
      ports: ["3389"]
      protocol: tcp
  assignments:
    - principalType: Group
      principalName: SEC-GSA-PA-DEMO-USERS
