apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: EIT_PrivateAccess_EIT_GH_DCs
  description: Private Access Domain Controllers – EIT_PrivateAccess_EIT-GH_DCs.
  owners:
    - florian.ried@extern.edeka.de
    - ertan.simsek@extern.edeka.de
  changeReference: EIT-PRIVATEACCESS-EIT_GH-DCS-001
  tags:
    workload: domaincontrollers
    pilot: "true"
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: RZ Sued Frontend
  destinations:
    - host: GR1W00001P001.int.edeka
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.127.128.11
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: GR1W00001P002.int.edeka
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.127.128.12
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: GR1W00001P003.int.edeka
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.127.128.13
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: GR1W00001P004.int.edeka
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.127.128.14
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
  assignments:
    - principalType: Group
      principalName: EIT_Intune_EIT_cfg Private Access PILOT
