apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: EIT_PrivateAccess_SB_DCs
  description: Private Access Domain Controllers – EIT_PrivateAccess_SB-GH_DCs.
  owners:
    - florian.ried@extern.edeka.de
    - ertan.simsek@extern.edeka.de
  changeReference: EIT-PRIVATEACCESS-SB-DCS-001
  tags:
    workload: domaincontrollers
    pilot: "true"
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: Suedbayern Frontend
  destinations:
    - host: sbs01dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.74.5.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs01dc02.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.74.5.110
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs01dc03.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.74.5.248
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs03dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.162.21
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs04dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.66.21
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs05dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.15.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs06dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.73.132.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs07dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.29.4.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs08dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.29.132.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs09dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.130.21
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs10dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.194.11
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs11dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.226.11
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs12dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.28.34.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs21dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.73.100.10
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: sbs212dc01.sb.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.73.240.133
      type: ip
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
  assignments:
    - principalType: Group
      principalName: EIT_Intune_EIT_cfg Private Access PILOT
