apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: EIT_PrivateAccess_RS_DCs
  description: Private Access Domain Controllers – EIT_PrivateAccess_RZS_DCs.
  owners:
    - florian.ried@extern.edeka.de
    - ertan.simsek@extern.edeka.de
  changeReference: EIT-PRIVATEACCESS-RS-DCS-001
  tags:
    workload: domaincontrollers
    pilot: "true"
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: RZ Sued Frontend
  destinations:
    - host: hesglodc1.rs.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.125.96.101
     type: ipAddress
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: hesglodc3.rs.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.125.96.103
     type: ipAddress
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: essglodc1.rs.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.125.96.100
     type: ipAddress
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: essglodc3.rs.edeka.net
      type: fqdn
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
    - host: 10.125.96.102
     type: ipAddress
      ports: ["88","123","135","389","445","464","636","3268","3269"]
      protocol: tcp,udp
  assignments:
    - principalType: Group
      principalName: EIT_Intune_EIT_cfg Private Access PILOT
