apiVersion: gsa.gitops/v1
kind: PrivateAccessApplication
metadata:
  name: PA-DEMO-SEGMENT-IPRANGE-START-END
  description: "Demo IP-Bereich Start–Ende – WinRM 5985 auf Connector-LAN (192.168.178.40–50)."
  owners:
    - platform@nuvatech.com
  changeReference: DEMO-SEGMENT-IPRANGE-START-END-001
  tags:
    purpose: demo
    segmentType: ipRange
spec:
  applicationType: enterprise
  isAccessibleViaZTNAClient: true
  connectorGroup: Office-Gersthofen
  destinations:
    - host: "192.168.178.40-192.168.178.50"
      type: ipRange
      ports: ["5985-5985"]
      protocol: tcp
  assignments:
    - principalType: Group
      principalName: SEC-GSA-PA-DEMO-USERS
